### PR TITLE
Download files from sharepoint

### PR DESCRIPTION
**Pull request by fatfingers23**
I have added the ability to download files from Share Point document libraries.
This does not use the ASP.net asmx services as it is [deprecated](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint#DeprecatedAPIs) and i would recommend SharePlum moving from it to Rest Api service for all new features and even moving old features to it.

This is downloading only. No uploads yet and nothing for attachments. I wanted to go ahead and push this change cause i am not sure when i will have time for uploads or attachments. Someone else can pick it up this is the [Microsoft Documentation](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest#working-with-files-by-using-rest) i used to add the Download features.

### CODE REVIEW

**Comment by jasonrollins** [comment]
I agree that REST is the better option for current SharePoint services.  The issue is that it doesn't work for older versions.  I've successfully used SOAP with SharePoint 2010 up to the Office 365 version.  If we add REST to the library I think we should make a clean break and remove all of the SOAP parts that will eventually stop working.  Can you confirm that this code works with SharePoint 2010?  I no longer have access to a server with this version on it.

**Comment by fatfingers23** [comment]
Well. I spoke too soon. It bothered me the ListData.svc was not working on Sharepoint 2013+. Well it does.
It is `/_vti_bin/ListData.svc/<ListName>` one i was trying had spaces. Took out spaces in Document library name worked like a charm. So this looks to be best end point, just have to be good with using older API which works across board, just deprecated and may be removed from Sharepoint online at anytime. Also would have to make sure to figure out how the List Names are formatted for the url there. Not sure if the formatting is always remove white spaces or what.

**Comment by jamesmcm** [comment]
I can't get this to work for a sub-site, with folders containing spaces - do they need to be encoded in some special way?

**Comment by fatfingers23** [comment]
It has been a long time since I've looked at this code or thought about it. Could try `_x0020_` as the space so the folder would be `Folder_x0020_ Name`.

**Comment by gwsampso** [comment]
@fatfingers23 GREAT PULL REQUEST made my life so much easier, i hate sharepoint.

Any idea on how to download a document into memory rather than to file path?

**Comment by jasonrollins** [comment]
I've finally added this functionality into the library.  It doesn't match your implementation though.  Have a look and see if what I've added will work for you.  I think I've got most of it covered now.  You have to state that you have SharePoint version 2013 or higher to get access to it.  I'm adding an example in the Readme.

**Pull request closed without merging**
