### PR TITLE
improved response handling, fixed flake8 issues

### PR DESCRIPTION
**Pull request by isaacnorman82**
Ok apologies first for bundling a few changes in one PR rather than separate ones.  I intended to just fix request response handling, but then found there were lots of flake8 issues, which might obscure any mistakes I made, so I fixed all the flake8 issues.

How the requests code now works:

There's a request_helper module that exports a get and post function (put/delete/etc could be implemented in future if needed).
These functions wrap and do exception handling.  Shareplum client applications need only catch ShareplumErrors.

Other changes/comments:

-Single place to get TEST_PASSWORD and assert if not set
-updated flake8 config to ignore some directories and long lines
-created a base exception class for shareplum 'ShareplumError' and a request specific ShareplumRequestsError for all request related exceptions
-office365.py calls requests.post with 2 positional arguments, should only have one, second should probably be data=body, I've fixed this to what I think it was meant to be
-fixed a bug in setting up https_adaptor in site.py init, max_retries=retry was just max_retries - showed up in flake8 errors
-fixed some references to _List that should be _List2007 (probably).  I'm guessing this code isn't really exercised as it wouldn't have worked.

Note: site get_site_templates looks like it has a copy and paste error - mid function return - unreachable code.  I haven't fixed this as I'm not sure what was intended.  I'll raise an issue.

In addition to the unit tests, I've also used this version in my app and it seemed fine (though it's not a particularly complex use case).

If you accept and merge this PR, please create a release and I'll move to using it.

### CODE REVIEW

**Comment by F2BA** [comment]
Hi, guys,

I don't know if it's related, but since this merge I can't auth anymore like below 
image

I get the following error:
image

Did anything change regarding this authentication approach?

**Comment by isaacnorman82** [comment]
I do:

authcookie = Office365(host, username=username, password=password).GetCookies()
site = Site(site_url, version=Version.v365, authcookie=authcookie)

And it works on 0.5.1

**Comment by jasonrollins** [comment]
Can you confirm that it works on a previous build?  There were no changes to the Office365 authentication code.

**Comment by F2BA** [comment]
It works for me in the 0.4.5

**Comment by jasonrollins** [comment]
I was assuming that your failure was on the line highlighted in red.  There are two changes made here, but I'm not sure how they are functionally different.  The requests posts are on lines 66 and 90.  If you change those back to "response = requests.post(url, body)" that would revert the change made.  I could build you a version to try, but I'm not sure how to get it to you.

**Comment by isaacnorman82** [comment]
I would recommend the following to test jason's suggestion above:

1. First make a virtual env with shareplum 0.4.5
-cd <your source root dir>
-python -m venv env_045
-active env (i.e. on windows env_045/Scripts/activate.bat)
-install 045 pip install -U shareplum==0.4.5
-deactivate env
2. Next make a virtual env with latest shareplum
-same as above but name env_051 or whatever and pip install that version

3. Run your code in 0.45 and see it works, with the _045 env active
4. Run your code in 0.51 and see it doesn't work, with the _051 env active
5. Copy office365.py from env_045/../sitefiles/shareplum/../ over the one in _051 env
You now have 051 but with office365.py from 045
6. Run your code in with _051 env active and see if it works.
If it works, there's an issue with my changes in this file.  Otherwise it's something else

To clean up after just delete the env directories.

Another thing that would be helpful is additional debug from the requests.  office365.py does two posts.  If you edit the request_helper.py file in env/../sitefiles/../shareplum

Add some prints to post:

```
def post(session, url, **kwargs):
    try:
       # something like print(f"url = {url}, args = {kwargs}")
        response = session.post(url, **kwargs)
        # something like:
        # print(f"status = {response.raw.status}")
        # print(f"status = {response.raw.headers}")
        # print(f"status = {response.raw.msg}")
        response.raise_for_status()
        return response
    except requests.exceptions.RequestException as err:
        raise ShareplumRequestError("Shareplum HTTP Post Failed", err)
```

Then you can share details of it failing in the newest shareplum version.  MAKE SURE YOU REMOVE ANY AUTH TOKENS FROM OUTPUT BEFORE SHARING.

**Comment by F2BA** [comment]
My code is in Azure Databricks and there I can only connect to a specific version of a lib (wouldn't be able to test by copying files between versions). 

And for company restrictions, I do not have the permission to test a request to this sharepoint site from outside Azure Databricks, so the only way would be having a new release.

My usage here is extremely simple so the version 0.4.5 works fine for me, then there is no problem if it's not possible to create a new release to test this. I informed so you could analyze the cenario better.

Thank you

**Pull request merged**
