### PR TITLE
Refactoring and handling Sharepoint Lists with validation

### PR DESCRIPTION
**Pull request by jamesmcm**
Hi,

This PR makes the following changes:

- Patches _List.get_list() to use xpath for extracting fields, etc. as the previous code failed to extract any fields from a List with validation enabled (an example is provided in tests/ - that test now passes in this PR but would fail on the current master branch) - note there are still some methods using fixed indices in the XML parsing to extract some data which should also be checked for possible problems.

- Renames method names to conform with PEP8 standards but aliases the old names so the current API can continue to be used i.e. _List.GetListItems() and _List.get_list_items() both work with the latter used for the definition.

- Splits the classes in to their own files to avoid one huge combined file. Note that the modules are import in \_\_init.py\_\_ so as to maintain the previous API i.e. shareplum.Site works - you don't need shareplum.site.Site

- Adds config for pre-commit, to run black and mypy when commits are made

- Adds type hints for mypy in most places

- Bumps the version to 0.3 to reflect the changes (mainly to remember to update the version, it doesn't need to be this number)

- Bumps versions of dependencies

I have only checked this with my usage in Python 3, if there are still users depending on Python 2 compatibility maybe this will cause issues, it would be great if someone could check that. In any case Python 2 is now fully deprecated so it might be best to drop support in the future anyway.

While this seems to be working now and should be mergeable, in the future it would be good to also add:

- A CI Build system on this repo, running the linters above (black, mypy, etc.) and the tests for all PRs

- More integration/unit tests and examples (I have added only one constructed XML response with validation)

- Docstrings (get pylint to pass on all documentation checks)

- Add logging for when exceptions are thrown, etc. (especially if these are recoverable)

- Bandit validation in pre-commit (this requires porting from lxml to defusedxml which is not trivial and the latter is also less frequently updated so this may not be worthwhile)

- Consider adding more optional dependencies to export Sharepoint Lists as Pandas dataframes and automatically deal with floats that get returned as strings like "float;#1.05000000000000"

Please let me know what you think, and try to test it with your use cases. This is a great library that has been incredibly useful.

### CODE REVIEW

**Comment by jasonrollins** [comment]
Very nice.  This is a lot of good work.  I don't have a way to verify that this works on SharePoint 2010, but I believe if it doesn't break anything for SharePoint 365 then it should work.  I'll check this and get back to you.

**Comment by jamesmcm** [comment]
Thanks, unfortunately our last Sharepoint 2010 instances were upgraded two months ago so I can't add a test case for that directly atm.

**Comment by jamesmcm** [comment]
I actually found we still had some Sharepoint 2010 Lists up so I added a test case with a fields envelope from Sharepoint 2010 too.

I tested pulling data on both 2010 and 2016 and it all works the same as before.

Please review this when you can @jasonrollins, as we're currently having to maintain a monkey patch for the List validation issue in Sharepoint 2016.

**Comment by jasonrollins** [comment]
Adding type annotations will break the Python 2.7 support.  Can we remove those to maintain Python 2.7 functionality?

**Comment by jamesmcm** [comment]
@jasonrollins done and verified on 2.7 and 3.8.

Note Python 2 is officially deprecated now, so it might be worth dropping support soon (especially since it means you can't use f-strings, as well as the awkward use of mypy).

**Comment by jamesmcm** [comment]
@jasonrollins would it be possible to merge this now? Also I see you created a new repo for shareplum2, I'd recommend applying the same refactoring (and really dropping Python 2 support there).

**Comment by jasonrollins** [comment]
That was the plan, but I think I'm going to dump it. SharePoint 2013 throws
a wrench in my whole plan. My new plan is to incorporate your changes, add
in some REST API stuff, and have the user tell me what what version they
are using then give them the features that are available. I'll probably put
in all of your changes immediately except the type hints. I'm not up to
speed on that yet so I'll need some time to digest it, but it shouldn't
take away any features.

So what I'll do is..
1. Implement your changes without the types.
2. Push that version to pypi as the last available version for py2.
3. Implement REST and new features, drop everything sub py3.5
4. Add typing.

**Comment by jamesmcm** [comment]
Sounds good, I think it'll also be easier for end-users having just the one module for both.

**Pull request merged**
