### PR TITLE
Add folders property to Folder class

### PR DESCRIPTION
**Pull request by isaacnorman82**
Add a 'folders' property - similar to existing filese property but returns names of child folders.

Other changes:
-updated .gitignore to ignore vs code workspace files
-my editor removed trailing whitespace, so there's a lot of whitespace change.  I think this is good practice.  Can undo if you'd rather not have this.

### CODE REVIEW

**Comment by jasonrollins** [comment]
I merged this in.  I checkout it out locally first and made a change to get
it to pass all of the tests.  Everything looked fine, but I just wanted to
test it out.  Let me know if this works for you.  I can my workflow to
whatever.  I'm not tied to anything.

Thanks!

**Comment by jasonrollins** [comment]
Should I delete the branch?

**Comment by isaacnorman82** [comment]
Yes, but I've done it now, thanks

**Comment by isaacnorman82** [comment]
What change was needed to pass the tests?  How do you execute your tests btw?

**Comment by jasonrollins** [comment]
if response.status_code != 201:  in self._create_folder().

If you go to the tests folder you run: python -m unittest.  Before it will
run you need to edit the test_server.json file with your information.  Then
to provide your password you need to export it into an environment variable
like this: export TEST_PASSWORD=********

So:
$ cd tests
# Edit test_server.json
$ export TEST_PASSWORD=********
$ python -m unittest

I'm up for suggestions to improving this flow.

**Comment by isaacnorman82** [comment]
I've just tried your tests, rather than comment here I've created an issue: https://github.com/jasonrollins/shareplum/issues/87

**Pull request merged**
