### PR TITLE
Change GetListItems() return all items when 'fields=True'

### PR DESCRIPTION
**Pull request by kaz399**
I want to get all items without designating all fields.

### CODE REVIEW

**Comment by jasonrollins** [comment]
What if we invoke your code when viewname=None and fields=None?  or
fields=True?  I don't have a problem with doing it the way you've done it
now, I just wonder if it would be better than 'fields=True'

**Comment by kaz399** [comment]
Thank you for your comment.

I think 'viewname=None and fields=None' is the better way.
Because of keeping compatibility, I took the way 'fields=True'.
If it is good for you that changing the default behavior of GetListItems(), I want to use  'viewname=None and fields=None'.

**Comment by jasonrollins** [comment]
Done.  Sounds good to me.  I'll work on putting this in unless you would
like to submit a patch.  It's all the same to me.

Thanks.

**Comment by kaz399** [comment]
OK.
I'll leave it up to you.
I'm looking forward to the next release.

**Comment by jasonrollins** [comment]
I've added this with [commit](https://github.com/jasonrollins/shareplum/commit/f98020e96895ecbf61716dfc8813ded122b16946).  Thanks.

**Pull request closed without merging**
